### ISSUE TITLE
Nice Work, Keep it up please. Add some extra features

### ISSUE THREAD

**Issue by MyFre3d0m** [engineerOWL/PEGASUS-HVNC-RAT#3]
Finally, you have opened this nice project.This project will destroy these scammers business who scam with people by selling Hiddenz v4.0.0 modification( just renamed and sell ) on HF.
However, I have a request for you to add some options...

1. Modification of password recovery folder (ClientsFolder) where We can see recovered password by name of HWID.It is very hard to find out the specific user who is in offline.Please,make it like LimeRAT recovery folder what is very efficient and memorable.
![HVNC_NEW Request](https://user-images.githubusercontent.com/112198848/188193338-10bce7e0-aa8e-4f2a-9a25-25701e648c9b.png)

2. offline Keylogger with unicode support and diffrent color in html format for easy read and understand.

3. Suspend and Resume process. 
4. User Idle time in a diffrent column
5. Always keep in Client .NET v4 not higher version.

Please, release a compiled version.
Love and respect from my heart for this nice project.

**Comment by engineerOWL** [comment]
> 

Thanks
I'm going to release the blue version as soon as it's updated and released in that The Pantheon keeps all versions of pegasus on the skynet server
Stealing the archive is easy for Grim1312
So as soon as I get the code, I will put it on my github profile.

![peauss](https://user-images.githubusercontent.com/108375436/188214949-ec94bc08-d300-49d0-a324-624cfa6812b7.png)
